# Imagen base
FROM python:3.11-slim

# Directorio de trabajo
WORKDIR /app

# Instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar backend
COPY main.py .

# Copiar frontend (index.html y style.css) dentro de /app/static
COPY frontend /app/static

# Exponer puerto (Render usa $PORT)
ENV PORT=10000

# Comando de arranque
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "10000"]
